export const Users = [
    {
      id:1,
      profilePicture: "./assets/persons/p1.jpg",
      username: "Safak Kocaoglu",
    },
    {
      id:2,
      profilePicture: "./assets/persons/p2.jpg",
      username: "Janell Shrum",
    },
    {
      id:3,
      profilePicture: "./assets/persons/p3.jpg",
      username: "Alex Durden",
    },
    {
      id:4,
      profilePicture: "./assets/persons/p4.jpeg",
      username: "Dora Hawks",
    },
    {
      id:5,
      profilePicture: "./assets/persons/p5.jpg",
      username: "Thomas Holden",
    },
    {
      id:6,
      profilePicture: "./assets/persons/p6.jpg",
      username: "Shirley Beauchamp",
    },
    {
      id:7,
      profilePicture: "./assets/persons/p7.jpg",
      username: "Travis Bennett",
    },
    {
      id:8,
      profilePicture: "./assets/persons/p8.jpg",
      username: "Kristen Thomas",
    },
    {
      id:9,
      profilePicture: "./assets/persons/p9.jpg",
      username: "Gary Duty",
    },
    {
      id:10,
      profilePicture: "./assets/persons/p10.webp",
      username: "Angelo",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "./assets/post/post6.png",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "./assets/post/post2.webp",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "./assets/post/post3.webp",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "./assets/post/post4.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "./assets/post/post5.webp",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "./assets/post/post1.png",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "./assets/post/post7.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "./assets/post/post8.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "./assets/post/post9.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "./assets/post/post10.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];